---
# handlers file for ara
- name: restart ara
  service:
    name: ara
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: 
  systemd: systemctl daemon-reload
    daemon_reload: yes
